# Generated by Django 5.1.2 on 2024-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perplexity_qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
