# Generated by Django 5.1.2 on 2024-11-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perplexity_qa', '0002_answer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.IntegerField(default=500),
        ),
    ]
